sudo: required

language: ruby
rvm:
 - 2.2
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec

services:
  - postgresql

before_script:
  - psql -c 'create database anna-portfolio_test;'
